### ISSUE TITLE
link to get OCIDs

### ISSUE THREAD

**Issue by chinmayjoshi-o** [cloud-partners/oci-prerequisites#1]
Can we add a link to this page to get OCIDs?
https://docs.cloud.oracle.com/iaas/Content/API/Concepts/apisigningkey.htm

**Comment by benofben** [comment]
I'm not sure I get this.  OCID for which?

**Comment by benofben** [comment]
...feel free to PR the repo as well...

**Comment by benofben** [comment]
Ah, I see.  Updated the links from Phoenix.  Thanks. https://github.com/cloud-partners/oci-prerequisites/commit/226344970f351852fd63ea692a8354d47cdca10e
